### ISSUE TITLE
Decide on the License of this game

### ISSUE THREAD

**Issue by zdavatz** [joe-the-ark/ark#1]
@joe-the-ark needs to decide on the License of this software. I suggest to use [GPLv3.0](https://github.com/zdavatz/yopenedi/blob/master/LICENSE)

**Comment by joe-the-ark** [comment]
![20201029_102135](https://user-images.githubusercontent.com/64843796/97549637-e58c4800-19d0-11eb-8f0b-1af46d5748db.jpg)

**Comment by zdavatz** [comment]
Good questions above. I hope I could answer them in our meeting.

**Comment by joe-the-ark** [comment]
Absolutelly @zdavatz --- thank you for your guidance!
