### ISSUE TITLE
The i18n choice is not working on localhost

### ISSUE THREAD

**Issue by LehaoLin** [joe-the-ark/ark#102]
With `django.po` and `django.mo` in the dir of `locale/en/LC_MESSAGES`, I run the project on my localhost. But the i18n choice is not working.(The screenshot which is that the language choice is English, but the content below is still German.)
![image](https://user-images.githubusercontent.com/35103106/107872852-5c9a0d80-6ee8-11eb-8a13-2ea4adbbf55e.png)

**Comment by joe-the-ark** [comment]
Ilya fixed the issue. The site is back to how it worked. 

Next task is to **solve the re-direct issue**. Ilya shared this idea, on how to find a solution
https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#the-set-language-redirect-view
![Hint](https://user-images.githubusercontent.com/64843796/108211356-e2a69600-712c-11eb-8ea5-c84519dfa9a4.jpg)
