### ISSUE TITLE
Analysing & visualising ark-data for scientific publication and learning

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#157]
The focus of this update is in analysing & visualising new data - less so on working with 'old' data. I changed the ark significantly in the last weeks. The basis for my research shall be all the data from here on.

For the ark data, I expect something simple, to start and learn data analysis myself. It has been such a fruitfull process to learn the basic programming techniques thanks to @zdavatz, @linker03, @reindexer and @oak-innovation, I can now develop the ark myself - how great is that? I would like to embark on a similar process to learn the ropes of data analysis and data visualisation. What do you think would be a good start? I think: Export the ark backend-data with a time-stamp, probably into excel? Some simple sorting functions (e.g. display only games after 1.8.2023) and some simple lists to start (what are the key terms that have been choosen the most), display of some key indicators per game in a list (e.g. psychological safety value, tension value, performance value), check if a game was finished and only include data of finished games. 

To start I am aiming at analysing across games. We have several key measures: 1) psychological safety score, 2) performance score, 3) tension score for that team. I want to display them per game to being able to compare them across games. One assumption that I observed: psychological safety score (e.g. 67 out of 99) & performance (e.g. 69 out of 99) are usually identical. While the tension level usually is in the area of 100 - psychological safety score (100 - 67 = 33 -> tension level). Just an example.

In I later stage, I maybe could make more use of an analysis per game or even per person in a game to replace the current pdf that is generated at the end of the game per user. Currently this would be nice to have, but has no high priority.

I just realise that (some of) these values are computed in the ark software. I am just wondering, can we re-use this code, e.g. calculating the tension score for a team in the headmap, or do we need to re-write?

**Comment by joe-the-ark** [comment]
Let's do a test with the game's data for ubung-2. Let's start with the game: NISIHOFTAKEOFF. Game is a 11 player game (if I remember correctly). Ubung-2 stores ONE value per player. The answer to the question <How good is your perceived team performance?> On a scale from 1-99. 

The average value in this game for Ubung-2 across all players is 53 – with 10 being the lowest value and 79 being the highest value:  If we are able to retrieve this data, for that game; then compare this value with the result for ubung-4 ( the psychological safety value: 69 in this case) > I am interested to see, how far these tgwo values are apart. To analyse on a game by game basis, how far or close the values for ubung-2 and ubung-4 are across all games.

One Hypothesis could be: these two values (between ubung-2 & ubung-4) are the further apart, the further the values for ubung-2 are away from one another (here the spread between high and low values for ubung-2 between 10 and 79 is kind of extreme). Or: these values are getting increasingly lower (ubung-2average 53 is kind of low), the further the values for ubung-2 are apart.

P.s.: Maybe one more thing - can we filter out the results from all the games that contain TEST in their name?

**Comment by zdavatz** [comment]
Always export into CSV Format. From there you can open in XLS, OpenOffice, etc. Question is: what are your data points? You could also export several CSV files and connect them via a UNIQUE ID.

**Comment by joe-the-ark** [comment]
Thank you for sharing your expertise @zdavatz – for the time being, I am going to be the end user. Interesting idea though, to open the data-set for the scientific community i na later step. 

In the first steps, I believe we go with what-ever format / toolset @reindexer is most comfortably with. Especially with regard to the goal, to ramp up my skills in the process to being able to hand-over the development of data-analysis one day in the near future.

p.s.: the ark-project has become pretty mature and robust. Maybe of interest for your mother? With regard to applications in her field of expertise? Everything we've talked / dreamed about in the early days is available, now. Open source, thanks to your much appreciated guidance.

**Comment by joe-the-ark** [comment]
Data-point map for an aggregated analysis and visualisation of game-data. Work in progress...
[23_09_data_points_ark.pdf](https://github.com/joe-the-ark/ark/files/12536292/23_09_data_points_ark.pdf)

**Comment by zdavatz** [comment]
Looks good for the start. How do you plan to visualize the group sentiment?

**Comment by joe-the-ark** [comment]
Thank you for your much appreciated feedback @zdavatz – I just jumped into the rabbit-hole. This is fascinating work. I begin to understand the fabric of data-points – so much complexity – so many options. I am trying to adapt, yet, this is a whole new universe. Babysteps on my learning journey.

As of now, I cannot answer your question. First, I want to get a feel for the available data. I am totally open for your ideas, Zeno. How would you go about visualizing? Which tools, graphs, languages would you use (Lingkai mentioned <julia>)?

**Comment by joe-the-ark** [comment]
Will share after the weekend, once the first two data-points with the highest priorities are implemented. Currently we are working with a django-script in the terminal. The results of a first prove of concept look like this...

**Comment by zdavatz** [comment]
1. I would anonymize all the players.
2. Where do I see who feels save and who does not feel safe?
3. I think it does not matter to know who feels safe and who does not feels safe. I think it matters more how many individuals feel safe and how many do not feel safe in the team.
4. I would assign all players random funny names. Always. Like this the person who feels unsafe never has to reveal his/her identity, but the team and team leader all have to work harder/smarter so all feel safe.
5. Btw, Twitter also cared about psychological safety.

**Comment by joe-the-ark** [comment]
1) Fair point, especially here on this site
2) this will become visible with #3 – value U5.b per player
3) well will see a number / percentage of votes outside the safe-zone. And a stress level for the team as a whole.
4) this does not work in the current implementation, because we work with feedback, self and other perception. I cannot (yet) imagine how to give feedback without an awareness whom I give the feedback
5) before or after elon checked in?

**Comment by joe-the-ark** [comment]
My thoughts on #157 @reindexer: we have come a long way, already. I can build on the analytics you've been programming. My only issue: can you think about a way to export the full data that is required to calculate the safe-circles?

**Comment by joe-the-ark** [comment]
CSV export per game for safe-circle-data with anonymous players done – thank you @reindexer
