### ISSUE TITLE
Old issue with SELF-NAMED LABELS in Gameflow Step 9 > ubung-5

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#38]
@linker03 & @LehaoLin 
**Issue: Labels of the tension scales are missing**

In Step 9 the players vote ALL the tension scales that have been named by all players in step 4 & step 6 in the game. There are as many rounds of voting as there are players. Because every player has voted one tension scale.

Include ONLY the players who made it to the waiting room – at the moment ALL players appear, even if they have not made it to the waiting room. And thus should not have been included into the starting team.  

**IMPORTANT**: the lower label has been defined in step 4 / ubung-1 / "Kraftquelle"   
The upper label has been defined in step 6 / ubung-3 / "Energiefresser"

![Step_9](https://user-images.githubusercontent.com/64843796/94432549-396bfd00-0197-11eb-8e7b-5d205147237b.jpg)

**Comment by joe-the-ark** [comment]
The old issue with self-named labels that are re-apperaring endlessly for voting, is here, again.
Please check game **ARK_EINS** – five player game, no safari. One player named an own label '**Kummer**' – now, all 5 players are stuck in an endless loop of four different scales with 'Kummer' at the bottom.
<img width="817" alt="Bildschirmfoto 2020-11-03 um 17 18 27" src="https://user-images.githubusercontent.com/64843796/98031291-8e440880-1e12-11eb-8edd-ec6e0c896b81.png">

**Comment by LehaoLin** [comment]
By checking the database, Opi and Joachim didn't play ubung5.

**Comment by joe-the-ark** [comment]
Solved.
@joe-the-ark : What is the solution for avoiding this issue in the future?
@LehaoLin : because pages of ubung1 and ubung3 are real-time data updated, I can’t make sure that the situation can be 100% avoided...but  I can reduce the accident possibility by making the backend code faster. Or we can use some rude regulations to correct it when players are waiting. Such like if two-records situation occurs, we just keep the newer record, but delete the older one.
@joe-the-ark : Keeping the newest record (if one or several records are present) makes sense to me.
