### ISSUE TITLE
Clean Up Team Heatmap Design

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#4]
@LehaoLin :: here is how to configure the team heatmap...

The Team Heatmap is an aggregation of all tension scale game data for all players combined on one sheet. The html frontend for the team heatmap is available in heatmap.html 

The Team Heatmap is an extra feature for professional facilitators. The heatmap is generated after every game and stored on the hosting server. 

Access the team heatmap through a link on the farewell page arche.html 
Password protect this access.

Here is a full description of how to build the Team Heatmap & an numerical example for some of the more complex calculations...
![Team_Heatmap_4](https://user-images.githubusercontent.com/64843796/97852047-8131f700-1cf6-11eb-925b-38e998298e52.jpg)

**Comment by joe-the-ark** [comment]
Is it possible to integrate the heatmap into THE ARK, yet, develop it in a separate repo for copyright reasons?

**Comment by joe-the-ark** [comment]
Here is numerical example for the most difficult calculation...
[Example_Team_Heatmap_7_Example.pdf](https://github.com/joe-the-ark/ark/files/5474682/Example_Team_Heatmap_7_Example.pdf)

**Comment by joe-the-ark** [comment]
This first version is looking good – two questions: 1) how can we get rid of the unnecessary column (marked yellow); 2) how can I technically charge money for access to the team heat-map (e.g. pay $100 via paypal to see the link)?  
![Graphics_Team_Heatmap](https://user-images.githubusercontent.com/64843796/98031896-78831300-1e13-11eb-971a-0537449ffcc0.jpg)

**Comment by joe-the-ark** [comment]
A simple request: please divide all the values on the heatmap by the square value x2 of the player numbers. Example: in a game of three, divide all values by 9. I a game of 4 divide all values by 16, etc.

**Comment by LehaoLin** [comment]
> A simple request: please divide all the values on the heatmap by the square value x2 of the player numbers. Example: in a game of three, divide all values by 9. I a game of 4 divide all values by 16, etc.

Done, please test it. Thanks.

**Comment by LehaoLin** [comment]
> This first version is looking good – two questions: 1) how can we get rid of the unnecessary column (marked yellow); 2) how can I technically charge money for access to the team heat-map (e.g. pay $100 via paypal to see the link)?

(1) is Done, please check it.
(2) I really don't know about paypal. We can't use paypal in China. And in China, I just know there are strict regulations to open the online payment in the web by using Alipay.

**Comment by joe-the-ark** [comment]
Thanks! I take this one off the table!!

**Comment by joe-the-ark** [comment]
@LehaoLin 
Minor issue on the Team Heatmap (see screenshot)
![Team_Heatmap_Numbers_New](https://user-images.githubusercontent.com/64843796/98545531-ead17880-2295-11eb-8fa0-9a7f07a56477.jpg)

**Comment by LehaoLin** [comment]
Done. Please check, thanks

**Comment by joe-the-ark** [comment]
Job done. Kudos. Dream Come true – you have no idea what we'll be doing with the heatmap!!

**Comment by zdavatz** [comment]
1. For Switzerland it would use Twint. They seem to have useable API.
2. PayPal should have a Sandbox where you can play around and test.

**Comment by joe-the-ark** [comment]
@LehaoLin : could you round the changed value to two digits after the comma – and maybe clean up the design? At the moment it has almost artistic quality, like a cubist painting by Paul Klee (Red Balloon, https://yunyistuff.wordpress.com/category/reading-paul-klee/) – poetic yet, very difficult to make sense of 
![Team_Heatmap](https://user-images.githubusercontent.com/64843796/98976445-a523e280-2517-11eb-94df-a29a769ed306.jpg)

**Comment by LehaoLin** [comment]
Done, please check

**Comment by joe-the-ark** [comment]
Thank you @LehaoLin for rounding the values. The headmap still looks fragmented – I ask @linker03 for help to free your focus for the backend work.
