### ISSUE TITLE
Debugging Gameflow between Step 15/16 > THIRD CHECKPOINT

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#42]
This is the third (of three) Check-Point in the game.
Check ARK_2_Gameflow.pdf in the frontend readme for an overview.
The function of this Check-Point is not yet programmed.

Here is the function of this Check-Point in step 15. 
**No player can move forward, until he has given feedback to everyone & all the other players have given feedback to him.**

A player can click on the "Weiterspielen" button in step 15, after he has given feedback to every teammate:
-> Feedback needs to be a minimum of 25 characters per field.
-> if all the feedbacks for the player from step 15 are in, the player moves on to step 16 to assessment.html
-> else, until all feedbacks for this player from step 15 are IN, display the following message to the waiting player "Warte bitte auf deine Mitspieler" or "Wait for your teammates"

**Comment by LehaoLin** [comment]
> -> Feedback needs to be a minimum of 25 characters per field.

This problem is a frontend stuff. I think the frontend team can fix js to implement it.

> -> if all the feedbacks for the player from step 15 are in, the player moves on to step 16 to assessment.html
> -> else, until all feedbacks for this player from step 15 are IN, display the following message to the waiting player "Warte bitte auf deine Mitspieler" or "Wait for your teammates"

I am doing them.

**Comment by LehaoLin** [comment]
Waiting step is done

**Comment by joe-the-ark** [comment]
@linker03 the missing gameflow condition should, according to @LehaoLin be programmed into #66

**Comment by joe-the-ark** [comment]
Thank you @linker03 & @LehaoLin
