### ISSUE TITLE
Use localise.biz to manage all translations

### ISSUE THREAD

**Issue by zdavatz** [joe-the-ark/ark#5]
Use [localise.biz](https://localise.biz) to manage all translations.

**Comment by joe-the-ark** [comment]
I contacted the support team from localise.biz – fingers crossed that they might be able to help.

**Comment by zdavatz** [comment]
what is the problem?

**Comment by joe-the-ark** [comment]
Hi @zdavatz - @LehaoLin did describe the problem, above (see p.s.) - in short: we tried a test page, step 2 in the game, preview.html - works fine if installed locally, but not on the server where it re-directs to Index.html.

P.s.: Here is @LehaoLin description of the issue "**I found that on the localhost, after POST "/i18n/setlang/", the client GET "first-mission" automatically, which is right; However, on the server, after POST "/i18n/setlang/", the client GET "/" automatically as we know the index.**

Weird."

**Comment by joe-the-ark** [comment]
Here is a quick reply from the loco-team: "Hello. 

This /i18n path you mention is not part of Loco. Possibly this is your application? 

I am only able to provide help using my platform. I don't see how your redirect problem could be related. If you still have a problem with this, please reframe your question in a context I can advise on. 

For example, it looks like you're using Loco to export PO files for Django. If there is a problem with these files, then feel free to ask about that.

Tim Whitlock 
localise.biz"

**Comment by zdavatz** [comment]
In which issue is the redirect problem mentioned? You should open a separate issue for the redirect problem.

**Comment by joe-the-ark** [comment]
Hi @zdavatz - yes, I consider opening a new issue. Currently, I have been keeping all translation related topics in this issue #5 - but it is getting complicated, I can see that...
