### ISSUE TITLE
Imroving Gameflow Step 8 / ubung-4.html > Better Mobile User Experience

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#54]
@linker03 :: another small request to improve the user experience: could you extend the size of the drop area in gameflow step 8? Instead of the yellow area (current situation) please extend it to the blue area. Thus treat the drop & corresponding text area as one big drop area. Result would be 6 bigger drop areas.
![Psychol_Saf_Area](https://user-images.githubusercontent.com/64843796/95690840-e8d6b400-0c1a-11eb-9cf8-4bf37570d125.jpg)

**Comment by linker03** [comment]
![mobile-ubung4](https://user-images.githubusercontent.com/26412480/97277400-a344f880-1862-11eb-87dc-cb4f8284c4a0.png)
How ubung-4 looks now.
