### ISSUE TITLE
SAFE ZONE POSITIONING MOBILE in Gameflow Step 12 > spannungsfelder.html

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#58]
@LehaoLin 
**Spannungsfelder is a result page for the player.** It shows the results from step 9 / ubung-5.html
Showing all the results on all voted scales that relate tom him. Thus all players see different results. **The only common element for all players is the safe zone**. It is calculated with the Scale-Median of all votes by all players on that scale as the anchor point +-16. The scale median is a game of four players has 16 votes per scale, because every one of the 4 players did cast 4 votes (one for himself and 3 for every one of his fellow players)  

**Player avatar is visible**, to remember him how he has been voting on himself.
**All other player avatars are blurred** – the results show how other players have voted on him – in step 14 / mission-2-ubung-1.html the player will be guessing, how the other players perceived him.

The **values in boxes** (in the example 15/65/65/15) are the difference of the self-vote of the player on that scale and how the other's perceive the player on that scale on average. Example in a game of four: Player sees himself on 39 – the other players see him on average at 49 (they voted him 34 / 49 / 64 on that scale). Thus Self Vote 39 - 49 (median how the others voted him) -> results in -10 -> Minus 10 is displayed in the box
<img width="372" alt="Bildschirmfoto 2020-10-14 um 08 54 39" src="https://user-images.githubusercontent.com/64843796/95954455-9f918a80-0dfb-11eb-8f6c-50696cab806b.png">

An important feedback element is the **colour code** (see screenshot for an example):
- White indicates an absence of tension. - Values above 16 indicate tension in the team.
- Red values indicate that the players self-perception is outside the psychological safe zone.
- Yellow values indicate that the players' perception by others is outside the psychological safe zone.
- Black values indicate that the players self-perception and the perception by others is outside the psychological safety zone of your team.
![Feedback_Page_12a](https://user-images.githubusercontent.com/64843796/95953561-42490980-0dfa-11eb-8e79-3e7c0df247ff.jpg)

**Comment by LehaoLin** [comment]
> If so. Then json like [{value:Effizienz Angst, status: 63}, {value:Effizienz Angst, status: 44}, ..... and so on ]

The value of `var json_list` is like. I think you can pick what you want from it.
![image](https://user-images.githubusercontent.com/35103106/97248613-22bfd100-183d-11eb-93e3-fc00672ddd54.png)

**Comment by linker03** [comment]
json_list have information only for one user. I need information about all user's votes.

**Comment by LehaoLin** [comment]
This is all other users voting to one person.
If you need all data, I have already updated to put all ubung5 data to the frontend, and you pick to use.
![image](https://user-images.githubusercontent.com/35103106/97290504-997fbd00-1883-11eb-9a0d-cc9e2e492589.png)

**Comment by LehaoLin** [comment]
> json_list have information only for one user. I need information about all user's votes.
> How this string in views.py should look like?
> `json_safezone = [ i.span_1 for i in list(Ubung5.objects.filter(goal=user)) ]`

This is all other users voting to one person(the present player).

**Comment by joe-the-ark** [comment]
Example for Safe Zone calculation:
![Example_Safe_Zone](https://user-images.githubusercontent.com/64843796/97316612-39c8e800-186a-11eb-854d-f79615583aa5.jpg)

**Comment by joe-the-ark** [comment]
@linker03 … cool, the Safe Zone is looking good. I see three small issues (see screenshot / example)...
![Feedback_Spannungsfelder](https://user-images.githubusercontent.com/64843796/97557063-92b78e00-19da-11eb-8374-77e178a07b36.jpg)

**Comment by joe-the-ark** [comment]
@linker03 :: in the mobile version of spannungsfelder I see two small issues (see screenshot / example): 1) change to the **matching three values in circles** once the scales change; 2) limit values in circles to **one decimal place** 
![Feedback_Spannungsfelder-Mobile](https://user-images.githubusercontent.com/64843796/97591435-eab4bb80-19ff-11eb-837b-f31fb6b45396.jpg)

**Comment by linker03** [comment]
I hope I'm done with spannungsfelder. Test, please.

**Comment by joe-the-ark** [comment]
Will do. Thank you for commiting. Cheerio Joe

**Comment by joe-the-ark** [comment]
Spannungsfelder is looking great! Love it.

I have seen one issue:
in **MOBILE** games the **positioning of the Safe Zone is not yet correct** – same as in #53

**Comment by joe-the-ark** [comment]
@linker03 documenting another minor issue in the mobile view of safezone in this video-clip: in a four player game only three of four tension scales are shown. While the navigation buttons for all four tension scales work, one scale is skipped (visible in the clip after 25 seconds).
https://youtu.be/UpxUh5LjhnU

**Comment by joe-the-ark** [comment]
Safe Zone looks good on MOBILE. Thank you @linker03 !
