### ISSUE TITLE
Improving Gameflow Step 14 / mission-2-ubung-1.html > implementing the game logic

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#63]
@LehaoLin 
Step 14 is the social sensitivity training.
Players have to guess how the other players voted them.
They **guess all the scales and all players, apart from themselves**. 
The gameflow is similar to step 9 / ubung-5

Yet, **additional game rules apply**: 
Players can only move to the next step in the game, once all values are green. 
An alert ("Bitte weitertrainieren, bis alle Werte grün sind") should be displayed, if player the wants to continue ("Weiterspielen"), while there are still Red or or unvoted items. 

Here are several examples to illustrate the different possibilities...
![ubung-6_f_c](https://user-images.githubusercontent.com/64843796/96555029-90a54f00-12b7-11eb-8c09-7556e0fda430.jpg)

**Comment by linker03** [comment]
> The correct answer json data I will transfer from the backend would be like
> `[ { id: 4 name: 'Vasilisa Kochetkova', avatar: '/static/images/avatars/boar.svg', statusSide: 50 }, { id: 5 name: 'Good Man', avatar: '/static/images/avatars/boar.svg', statusSide: 77 }, ]`

What I need type in {{ }} to get this ^^^ data ?

**Comment by LehaoLin** [comment]
`{{ member_list | safe }}`

**Comment by linker03** [comment]
`let rightChoice = {{ member_list|safe }};`

And got this 
![right_choice](https://user-images.githubusercontent.com/26412480/97775666-cd612800-1b8c-11eb-9d80-18268e65ae77.png)

**Comment by LehaoLin** [comment]
Try it now. I just update the code.

**Comment by LehaoLin** [comment]
@linker03 
Try it now. I just update the code.

**Comment by joe-the-ark** [comment]
This social sensitivity vote is almost done. Here are, again, the 1) game-mechanics for the player to pass & a 2) sketch for the visual feedback:

1) **game-mechanics**: all players need to vote all scales – a player can only continue to the next scale, once all his guess values are green – which means within a range of +-4 from the true value.
2) here is a **sketch for the visual feedback**: how it looks now & how it should look like in the four different possibilities (guessing far too high, guessing far too low, guessing almost right, guessing exactly right)
![Empathy_Scale_1](https://user-images.githubusercontent.com/64843796/98042755-61005600-1e24-11eb-8a17-005cc96238bc.jpg)

**Comment by LehaoLin** [comment]
Have a try, Joe.

**Comment by LehaoLin** [comment]
@joe-the-ark 
Have a try, Joe.

**Comment by LehaoLin** [comment]
@linker03 
linker03, can you show me how to control the color of numbers?

**Comment by linker03** [comment]
![image](https://user-images.githubusercontent.com/26412480/98477991-cf785600-2220-11eb-9447-eb065a83ff16.png)
Here through CSS property filter.
https://css-tricks.com/almanac/properties/f/filter/

**Comment by LehaoLin** [comment]
Thanks

**Comment by LehaoLin** [comment]
@linker03 
Thanks

**Comment by LehaoLin** [comment]
@linker03 
Joe left this instruction:
> Last two things: 1) could we display the "guessed value" INSIDE the circle instead of the avatar, if the values are outside the interval true value +-4 --- and 2) could we display a bigger avatar, just like in my design sketch, to give the player a clear visual feedback, if the guess value is inside the interval true value +-4?

I don't how to transform between the avatar and the number value by the condition in the `AppGraph.js` file. (please git pull the newest code. I updated the file to do the color transformation). And I think the 2nd requirement relates the mobile device scale change. I think you are more familiar this `AppGraph.js` and css than me. I am worried to break the code, because I know it may be used in other pages. Can you help me to deal with it? Thanks!

**Comment by linker03** [comment]
@LehaoLin Make please mechanism preventing to proceed if guess value and true value is different. 
`game-mechanics: all players need to vote all scales – a player can only continue to the next scale, once all his guess values are green – which means within a range of +-4 from the true value.`
I'll make color and avatar.

**Comment by joe-the-ark** [comment]
As a response to @linker03 question above: @LehaoLin did implement this condition, already. I tested it yesterday. Worked.

**Comment by joe-the-ark** [comment]
KUDOS. Thank you for finishing the task @linker03
