### ISSUE TITLE
Improving Gameflow Step 15 Feedback / mission-2-ubung-2.html > implementing the game logic

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#66]
@linker03 could you remind me if / how a player could skip feedbacks for selected players? That was part of the first frontend proposal: is this idea still subject to implementation?

Gameflow & Checkpoint is described in #42 

Focus should be in the first-text-box – with a red frame to guide the attention of the player. 

Basically every player answers the three questions in the box – minimal 25 signs per box – alert message, if less signs have been used.

I made a little sketch with an example and the most important information to integrate this page...
![Feedback_Description](https://user-images.githubusercontent.com/64843796/97175651-21869980-1794-11eb-90f8-b5e93ced9baa.jpg)

**Comment by linker03** [comment]
@LehaoLin  How can I check forms before submitting?  I have a function for checking textareas, but I don't understand where should I insert this function.

**Comment by linker03** [comment]
I Figured out

**Comment by joe-the-ark** [comment]
Thank you for committing Ilya!!

**Comment by linker03** [comment]
![submit](https://user-images.githubusercontent.com/26412480/98385409-24796800-2079-11eb-8c91-fcfc696207f1.png)
With that condition we don't wait other players any more. 
@LehaoLin Let's think how to check forms before submiting.

**Comment by LehaoLin** [comment]
Sorry, I don't get the idea why we don't wait other players anymore.

**Comment by LehaoLin** [comment]
@linker03 
Sorry, I don't get the idea why we don't wait other players anymore.

**Comment by linker03** [comment]
![vue](https://user-images.githubusercontent.com/26412480/98436214-deb5b180-2103-11eb-9904-91f662b4e87f.png)
Maybe we can add checking in some of this vue? Which of them decided to wait others?

**Comment by linker03** [comment]
Maybe 
`function check_finish() {
    if (app1.loading ===true && formValidator()) {
.................`

**Comment by LehaoLin** [comment]
I think we need Joe to decide it. @joe-the-ark

**Comment by joe-the-ark** [comment]
@linker03 : I found two very small details that could be improved...
![Feedback_Feedback](https://user-images.githubusercontent.com/64843796/98450606-3bce5900-213e-11eb-9bc3-0f60306d6884.jpg)

**Comment by joe-the-ark** [comment]
Seems to work --- will do some more testing tonight...
