### ISSUE TITLE
Building Gameflow Step 16 Assessment > Players Results

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#74]
@linker03 :: this is the last element
Step 16 displays all the game-data of a player. 
The player can download this page as a pdf.

I compiled a sketch made up of the four elements of this assessment page.

1) **Team Performance Scale**.
2) **Feedback from other players** and oneself based on three questions.
3) **Psychological Safety Score** with all votes / avatars of all players visible instead of the blurred view in step 11.
4) All the **content from spannungsfelder** – without navigation, because these results should be printable / storeable in a PDF
![Assessment_Mockup_3](https://user-images.githubusercontent.com/64843796/97815000-7726de80-1c8b-11eb-90fb-c3cdb772b8d0.jpg)

**Comment by linker03** [comment]
@LehaoLin   I can't reach this step (ERR_TOO_MANY_REDIRECTS). Can you check this, please?

**Comment by joe-the-ark** [comment]
Hi @linker03 --- anything I can do or check to support?

**Comment by joe-the-ark** [comment]
#75 relates to this issue and specifies an aspect.

**Comment by joe-the-ark** [comment]
The basics are there. I split this up into smaller issues.
