### ISSUE TITLE
Text in the boxes is wrong in step 16 assessment > Psychologischer Sicherheitswert

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#75]
@linker03 
One improvement of the assessment page #74 is to show the players avatars in step 16. In that section we should **see how every players has been voted for** by the other players.
@LehaoLin : could you check, if we do have this data in the backend? If so, which variable can we use to show the right avatar in the right place (see screenshot)?
<img width="587" alt="Bildschirmfoto 2020-11-08 um 10 23 56" src="https://user-images.githubusercontent.com/64843796/98461549-4116bc80-21ad-11eb-88a2-1fe7fc38f4ca.png">

**Comment by linker03** [comment]
@LehaoLin  can you make data from backend like objects. Example:
`row1  = [
{avatar: "/static/images/avatars/dog-1.svg"
name: "init"},
{avatar: "/static/images/avatars/boar.svg"
name: "p1"},
{avatar: "/static/images/avatars/cat.svg"
name: "p2"},
]
`

**Comment by linker03** [comment]
```
<div class="distry__user" v-for="count in row5">
       <img src="/static/images/avatars/dog-1.svg" alt="">
 </div>
```
This how it used to be. Than avatars will be visible

**Comment by LehaoLin** [comment]
@joe-the-ark 
Joe, do i need to make the value in the user list be distinct in every position?

**Comment by LehaoLin** [comment]
Done, please check.

**Comment by joe-the-ark** [comment]
@linker03 --- @LehaoLin did solve the avatar visibility issue.

However, I just noticed another bug in step 16 assessment: the **text descriptions in all the 6 boxes are identical** (screenshot)
<img width="1006" alt="Bildschirmfoto 2020-11-09 um 21 46 54" src="https://user-images.githubusercontent.com/64843796/98594973-a9f95400-22d5-11eb-8b69-68997937ec05.png">

**Comment by linker03** [comment]
I'm changed containers description in assessment 

Will avatars visible in psychologischer too ?

**Comment by joe-the-ark** [comment]
Hi @linker03 - good morning - no, avatars will not be visible in psychologischer

**Comment by joe-the-ark** [comment]
Excellent! Works!! Solved!!!
