### ISSUE TITLE
Serious Scale Labelling issue in step 9 / ubung-5 

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#76]
@LehaoLin 
All players are getting the same scales with the same two labels (Ehrgeiz / Ehrgeiz)
Players can endlessly re-vote that same scale... Same issue on all browsers & mobile. 
<img width="1376" alt="Bildschirmfoto 2020-11-08 um 20 16 20" src="https://user-images.githubusercontent.com/64843796/98482164-de9adc00-21ff-11eb-9bee-c4a8e7522443.png">
____________________
Same game, changed to landscape mode – only one scale label appears...
<img width="851" alt="Bildschirmfoto 2020-11-08 um 20 27 25" src="https://user-images.githubusercontent.com/64843796/98482308-db542000-2200-11eb-935d-86ddb15736ee.png">

**Comment by LehaoLin** [comment]
Just a bug is found and solved. Please restart a new game. Sorry for that bug.

**Comment by joe-the-ark** [comment]
All good! My testing work would be useless,  if I'd not come across the occasional bugger
