### ISSUE TITLE
Issue between mission-2-ubung-1.html & mission-2-ubung-2.html 

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#77]
@LehaoLin 
Feedback page appeared in a strange version & error code
![Screenshot_20201108-222545_Firefox](https://user-images.githubusercontent.com/64843796/98484747-dcda1400-2211-11eb-8792-5bbff49ca3bf.jpg)
![Screenshot_20201108-222559_Firefox](https://user-images.githubusercontent.com/64843796/98484749-dea3d780-2211-11eb-95e7-823becdd7a9d.jpg)

**Comment by LehaoLin** [comment]
Is the bug still there? I just found the server was not updated.

**Comment by joe-the-ark** [comment]
Could not test, yet, because my players are stuck between step 10 / 11

**Comment by joe-the-ark** [comment]
The issue has been: "To many on-call connections to the server"
