### ISSUE TITLE
Vote values are mostly wrong in step 16 assessment > Spannungsfelder

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#78]
If you are looking at the screenshot, you notice, that all values for the player on the scale are identical. These values are the values that the players themselves have voted. Yet, on these scales, every player should see how the others (plus self-vote) voted for him. Simple change of variables. That bug was present in spannungsfelder, too, @LehaoLin corrected it.
<img width="578" alt="Bildschirmfoto 2020-11-09 um 21 46 08" src="https://user-images.githubusercontent.com/64843796/98596778-3a389880-22d8-11eb-9c7a-772933c6fdbf.png">

**Comment by linker03** [comment]
I didn't understand. Should I do something with assesment and spanungsfelder or everything is done already?

**Comment by linker03** [comment]
![image](https://user-images.githubusercontent.com/26412480/98629959-3fcbc800-2344-11eb-8ac5-0d8365655539.png)

**Comment by joe-the-ark** [comment]
hi, spannungsfelder has already been done some days ago.

**change should be done in assessment**

**Comment by joe-the-ark** [comment]
Solved. Kudos. Thank you @linker03
