### ISSUE TITLE
Still an issue with step 9 / ubung-5 > Scale with only one label

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#79]
@LehaoLin 
5 player game, all labels chosen from the list – apparently one choice went unnoticed – in step 9 / ubung-5 appears a scale with only one label "GLEICHBERECHTIGUNG" – upper side is empty – once the players get there the game is stuck.
<img width="1437" alt="Bildschirmfoto 2020-11-09 um 23 03 52" src="https://user-images.githubusercontent.com/64843796/98602333-96071f80-22e0-11eb-97c7-57b0b94bf31d.png">

**Comment by LehaoLin** [comment]
Really old bug. Just a double ubung-1 record problem and it has already solved before. I think it will not happen again.

**Comment by joe-the-ark** [comment]
Hi @LehaoLin – yes, I know, we have had this bug several times in the last weeks. And it happened twice in three games today. What can we do to prevent it?

**Comment by LehaoLin** [comment]
Sorry for this bug, I forgot to save the data in my debug code.
Now, the problem is solved, I think.

**Comment by joe-the-ark** [comment]
Thanks @LehaoLin – I keep the issue open until I've done more testing, later today.

**Comment by joe-the-ark** [comment]
This issue is solved, yet I found another one related to ubung-5 – maybe related?
