### ISSUE TITLE
Still an issue at second checkpoint

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#80]
As soon as two or more players are waiting, the **response time gets really, really slow** – in a five player game I had to wait a minute until I could play on.
I believe the issue relates to the waiting routine – maybe it is checking too often? Or is it written in vue that is otherwise not used in the project? In my opinion, something is seriously wrong at the second checkpoint.

There is a similar issue at checkpoint three.

Maybe it is even a similar problem than in #79 – because when we chose the scale labels, we are getting the same fancy black background that might cause problems? Is there another, more simple and less resource draining way? 
<img width="1407" alt="Bildschirmfoto 2020-11-09 um 23 41 56" src="https://user-images.githubusercontent.com/64843796/98605642-111f0480-22e6-11eb-937b-d67754f9f414.png">

**Comment by LehaoLin** [comment]
I think this issue can be closed.

**Comment by joe-the-ark** [comment]
I trust you on this one @LehaoLin
