### ISSUE TITLE
Feedback > autopilot to empty fields...

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#81]
@linker03 in the example all textfields a filled – in an older version, once I pressed "Weiterspielen", I was automatically taken to another player with empty fields and could give my feedback there, until all feedback were given. I really liked this much better. Could you re-write this function?
  
<img width="883" alt="Bildschirmfoto 2020-11-10 um 00 28 16" src="https://user-images.githubusercontent.com/64843796/98609435-893cf880-22ed-11eb-93d1-797553233b1f.png">

**Comment by linker03** [comment]
Done.

**Comment by joe-the-ark** [comment]
Works like a charm – thank you @linker03 !
