### ISSUE TITLE
Psychological Safety Score Value not recorded

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#82]
In the 3 player test today, one value in ubung-4 has not been recorded. The player could pass despite he had only cast 2 instead of 3 votes.
Evidence: in assessment there are only 8 instead of the normal 9 votes (screenshot)
![Bug_Psychological_Safety_Score](https://user-images.githubusercontent.com/64843796/98685002-24be7f80-2367-11eb-9463-588335bbf76f.jpg)

**Comment by LehaoLin** [comment]
What's this game name?

**Comment by joe-the-ark** [comment]
ZKB-Spiel
Player who's value was not recorded is Ändu – or something like this...

**Comment by LehaoLin** [comment]
Somebody left blank and didn't vote everyone.
Does the user have to vote everyone?

**Comment by joe-the-ark** [comment]
Yes.

**Comment by LehaoLin** [comment]
Ok, let me add the condition.

**Comment by joe-the-ark** [comment]
Thank you @LehaoLin for fixing this!

**Comment by joe-the-ark** [comment]
Hi @LehaoLin – something strange happened after you changed the condition – the entire voting area disappeared (screenshot) for all players in a 5 player game...
<img width="1366" alt="Bildschirmfoto 2020-11-10 um 21 00 56" src="https://user-images.githubusercontent.com/64843796/98727410-28b6c580-2398-11eb-8729-15d3ed808455.png">

**Comment by LehaoLin** [comment]
From the frontend console, the problem is not from my change. It is from other two js cdn. I think we need @linker03 to fix it.
