### ISSUE TITLE
Bug: Fix the min/max length of the Username inputfield

### ISSUE THREAD

**Issue by LAFLAME55** [joe-the-ark/ark#84]
Sounds  like a good idea @LehaoLin – what do you think?
______________  
Hey everyone

I've tested your Application and I've found this Bug (by attached Files). You should add to the input Field the keywords: maxlength="20" and the minlength="2". The numbers are for the amount of the characters. When you fixed this bug, the UI will look much better :) . 

Wish you a great day.

Best Regards

Serkan
<img width="890" alt="Screenshot 2020-11-12 115701" src="https://user-images.githubusercontent.com/72396088/98931446-51e16e00-24de-11eb-88f3-0d037a8a0762.png">

**Comment by LehaoLin** [comment]
Done, please check.

**Comment by joe-the-ark** [comment]
@LehaoLin :: I did update the server, but the conditions seem not yet apply
<img width="1153" alt="Bildschirmfoto 2020-11-12 um 20 27 10" src="https://user-images.githubusercontent.com/64843796/98986651-7d3b7b80-2525-11eb-9f30-fb1263b9e76e.png">

**Comment by LehaoLin** [comment]
Please check again. Thanks.

**Comment by joe-the-ark** [comment]
All good! Thanks for solving!!
