### ISSUE TITLE
One scale does not show in ubung 5 / all players stuck at checkpoint 2

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#85]
@LehaoLin 
7 player game, 6 make it to the waiting room, thus 6 start into ubung-4 &  ubung-5. 
BUT: in ubung-5 players can only vote 5 scales – **maybe the first scale selections in ubung-1 & ubung-3 have not been recorded in the database**? – I noticed, because the chosen labels have not been crossed through in ubung-1 & ubung-3 --- here is the screenshot of one of the 6 players stuck at checkpoint 2...
Maybe we need a check, before entering the waiting room for every player, if he has chosen the labels in ubung-1&3 – and if not, present him these tasks, again. 
<img width="1364" alt="Bildschirmfoto 2020-11-15 um 20 38 58" src="https://user-images.githubusercontent.com/64843796/99195018-7611a900-2783-11eb-9ecf-1c135e9eb8bf.png">

**Comment by LehaoLin** [comment]
I checked from the database, and found Maxi didn't vote in the ubung1 and ubung3.

**Comment by LehaoLin** [comment]
Solved. Add a new checking section to check whether the user's ubung1 and ubung3 record are in the database.

**Comment by LehaoLin** [comment]
Solved. Add a new checking section to check whether the user's ubung-1 and ubung-3 record are in the database. And the checking part is in the waiting room page. If someone's ubung-1 or ubung-3 record is missed, the page will redirect to ubung-1/ubung-3 page to make the user play again.

**Comment by joe-the-ark** [comment]
Excellent!! That makes sense. I'll do more testing today after my workday.
