### ISSUE TITLE
Speed & Response time issues > the game is currently unplayable on my server

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#86]
@reindexer 
@LehaoLin 
The game in its current version is unplayable on my server. I tried to complete several 7 player games today and did not succeed. I had very long waiting times. Can I have your assessment, please, what does it takes to make the game playable on my server?

What could be the root-cause? 1) Server speed, 2) database, 3) code that causes unnecessary parallel processes, 4)...? 

Input to the root-cause analysis: 
1) the virtual resources of the server are 1GHz CPU and 2GB RAM
2) @LehaoLin changed the database to MySQL which brought some improvement > what are alternatives to improve DB speed?
3) @LehaoLin in recent unsuccessful tests mentioned the killing of unnecessary django-processes to unstuck the game-flow – maybe these processes could be avoided from the beginning by improving the software code?   
4)...

Answers:
1) Let's see if Hosting is the issue. I registered to AWS. @LehaoLin could you please change the vserver & install THE ARK on the new account...
2)
3)
4)...
Screenshot from today's test...

Current situation (screenshot):
<img width="1438" alt="Bildschirmfoto 2020-11-17 um 12 29 09" src="https://user-images.githubusercontent.com/64843796/99395003-1d0b5780-28e0-11eb-8abb-a947a31a96ce.png">

**Comment by joe-the-ark** [comment]
@zdavatz :: can I ask you for an experienced guess Zeno? How fast do you think a server should be to host THE ARK? Do you think 1c 2gb could be the bottleneck?

**Comment by zdavatz** [comment]
I would go for at least 4 GB of RAM. Use `htop` to monitor the Server resources while playing with 7 or more players.

**Comment by joe-the-ark** [comment]
Thanks @zdavatz --- my current host does not offer 4c 4gb - I consider hosting at aws --- would you recommend another hosting service? 

Thanks for the htop reference - you're recommendation is to instal htop on the Linux server & access it through the Mac terminal, right?

**Comment by zdavatz** [comment]
Yes. Something like `sudo apt install htop`

**Comment by joe-the-ark** [comment]
@zdavatz @LehaoLin @reindexer 
VServer updated, up & running
<img width="300" alt="Bildschirmfoto 2020-11-23 um 12 49 39" src="https://user-images.githubusercontent.com/64843796/99959011-9d233880-2d8a-11eb-84be-2c1e9113d1c2.png">

**Comment by zdavatz** [comment]
Keep us posted if this helped or not.

**Comment by joe-the-ark** [comment]
@zdavatz the server upgrade worked to solve the issue! The game is now playable without bugs!! Enjoy & thanks so much for your much appreciated company on this journey, so far Zeno!!

**Comment by zdavatz** [comment]
To be continued! ;) How is it going with the translations?

**Comment by joe-the-ark** [comment]
No solution for the translation #92 issue so far.

**Comment by joe-the-ark** [comment]
But Lingkai is looking into it == there is hope
