### ISSUE TITLE
Stop Mulitple Reloads of the Slider in Mobile ubung-5 & mission-2-ubung-1

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#87]
@linker03 
I noticed this **minor issue with the slider in mobile** games in ubung-5 & mission-2-ubung-1:
The page reloads reloads twice before a player can start voting and erases all previous input on the slider. 

And the page reloads every time after the screen has been moved / scrolled up or down. In games with more than 10 players you'll have to scroll down, because not all players will fit on one screen. This scrolling will erase all previous inputs on the slider.

**Could you look into what causes these unnecessary reloads and stop them?**

**Comment by linker03** [comment]
The reload occurs only when the window size changes. In my browser, I can't replay that bug. I'll test it on my phone when test.arks.ch will work again.

**Comment by joe-the-ark** [comment]
Hi Ilya, the bug only occurs on mobile. Please test on your phone.

The game moved to arks.ch

test.arks.ch is no longer server.

**Comment by linker03** [comment]
I made some fixes. Upload please, the fresh version to the server.

**Comment by joe-the-ark** [comment]
Perfect. Solved!! 
Thank you so much. Much more enjoyable to play!!!
