### ISSUE TITLE
10/2021 > Clean Up Team Heatmap

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#89]
Hi @linker03 - could you help cleaning up the team heatmap & **fix the known display-issues of the team heatmap (at the moment the matrix is not aligned in 4 player+ games). **

But with more players in the game strange things happen in the design. E.g. unwanted breaks, columns shifting in wrong places... **Here is an example of the current design in a six player game and how it should look-like**, more or less like a cleaned version of the three player heatmap... (Screenshot & Photoshop sketch before & after...)

![Heatmap_next_version_2](https://user-images.githubusercontent.com/64843796/139076920-991fb2ce-7658-45fd-89db-3b461de85f9a.jpg)

**Comment by linker03** [comment]
Solved. Check, please. I have tested it with four players

**Comment by joe-the-ark** [comment]
Thank you @linker03 – much appreciated!

**Comment by joe-the-ark** [comment]
@linker03 
Teammap still looks awkward (see screenshot).
Is this an old version?
The values in the top row should be only two after-digits. We had fixed this already.
<img width="654" alt="Bildschirmfoto 2020-11-24 um 21 45 46" src="https://user-images.githubusercontent.com/64843796/100149659-d2b94600-2e9e-11eb-9534-528e8941269d.png">

**Comment by joe-the-ark** [comment]
@linker03 
Teammap still looks awkward (see screenshot).
Is this an old version?
The values in the top row should be only two after-digits. We had fixed this already.
<img width="654" alt="Bildschirmfoto 2020-11-24 um 21 45 46" src="https://user-images.githubusercontent.com/64843796/100149659-d2b94600-2e9e-11eb-9534-528e8941269d.png">

**Comment by linker03** [comment]
Looks like the problem is in not rounded numbers above avatars. @LehaoLin can you round these numbers?

**Comment by joe-the-ark** [comment]
Yes, I agree. The rounded numbers are only a detail. I will test with different browsers, soon. Maybe I'll see then a path to solve this...

**Comment by LehaoLin** [comment]
Done, please check.

**Comment by joe-the-ark** [comment]
Thanks @LehaoLin 
Heatmap looking great, now! Kudos
<img width="882" alt="Bildschirmfoto 2020-11-25 um 18 27 00" src="https://user-images.githubusercontent.com/64843796/100262115-00a89400-2f4c-11eb-831f-a01dbc0a8781.png">

**Comment by joe-the-ark** [comment]
@linker03 
In a 9 player game, the heatmap is still slightly out of order. If there is an easy fix, please consider giving it another shot.
<img width="1086" alt="Bildschirmfoto 2020-11-26 um 23 58 51" src="https://user-images.githubusercontent.com/64843796/100443314-c3f2af00-30a9-11eb-94d8-83b5dc202701.png">

**Comment by linker03** [comment]
@LehaoLin  Is there any chance to get the same page as Joe here? I mean downloading from the database that state and request heatmap with that state?

**Comment by linker03** [comment]
Some styles are broken. I can't reproduce it on my computer.
![image](https://user-images.githubusercontent.com/26412480/100446540-3038d700-30d9-11eb-8738-6760006a5d3a.png)
@joe-the-ark can you show me styles like this:
![image](https://user-images.githubusercontent.com/26412480/100446646-5eb6b200-30d9-11eb-9230-694b60f99e06.png)

**Comment by joe-the-ark** [comment]
@linker03 
Does this help?
<img width="1349" alt="Bildschirmfoto 2020-11-27 um 14 20 32" src="https://user-images.githubusercontent.com/64843796/100453983-484e2d80-30bc-11eb-94e5-9c2eff5c2a27.png">

**Comment by linker03** [comment]
Nope. Maybe English chrome would help. 
![image](https://user-images.githubusercontent.com/26412480/100462246-2e304180-30f4-11eb-87c8-85d9070b3ab5.png)

**Comment by joe-the-ark** [comment]
Solved. Moved the player names to the bottom & replaced "mean" by "sum" in the last line. So proud. I can do it!
