### ISSUE TITLE
Weired /i18n path re-direct issue only on the server

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#92]
> Maybe it's in the nginx settings, not django

I checked the Nginx. The bug is not from the Nginx.

**I found that on the localhost, after POST "/i18n/setlang/", the client GET "first-mission" automatically, which is right; However, on the server, after POST "/i18n/setlang/", the client GET "/" automatically as we know the index.**

Weird.

_Originally posted by @LehaoLin in https://github.com/joe-the-ark/ark/issues/5#issuecomment-712783486_

**Comment by joe-the-ark** [comment]
@linker03 wrote "What's the purpose of the index page? I thought it's only for frontend demonstration and later project will start from auth page."

**Comment by joe-the-ark** [comment]
@joe-the-ark answered "...in the final version the initiator / player will never see the index-page.
Because the initiator enters the game through https://test.arks.ch/initiate/
And the player joins in through https://test.arks.ch/link/..."

**Comment by joe-the-ark** [comment]
This came up during the security check – maybe part of the solution?
<img width="412" alt="Bildschirmfoto 2020-12-04 um 13 56 47" src="https://user-images.githubusercontent.com/64843796/101166468-9de48600-3638-11eb-9115-20442be3daa6.png">

**Comment by zdavatz** [comment]
What are the steps to reproduce the issue?

**Comment by joe-the-ark** [comment]
https://youtu.be/QpK-brSnWnk

**Comment by joe-the-ark** [comment]
Here is maybe a key to solve this bug.

I was wondering where the translation text comes from – should be from localize.biz
Notice the spelling of "Social sensitivity" – sensitivity written with a small cap.
![WhatsApp Image 2021-01-06 at 15 20 38](https://user-images.githubusercontent.com/64843796/104337870-3999c980-54f6-11eb-851c-4edc39618d69.jpeg)

However in the translation interface on loco, as you can see, "Social Sensitivity" is written with two Uppercase letters. Could it be that the translation content at the moment does not come from loco, but from another source? If so, what is the source?
![WhatsApp Image 2021-01-06 at 15 22 37](https://user-images.githubusercontent.com/64843796/104338100-72d23980-54f6-11eb-9f73-dd6473a74799.jpeg)

**Comment by joe-the-ark** [comment]
Thank you @linker03 & @xaoni for fixing this!
