### ISSUE TITLE
Fix Psychological Safety Value Display in step 11 / psychologischer.html with the code from step 16 / assessment.html

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#93]
@linker03 
The psychological safety display in step 11 / psychologischer.html is broken. Colour scheme and positioning of the value on the scale is wrong (see screenshot 1).

Please take the psychological safety display code from step 16 / assessment.html – here everything works perfectly (see screenshot 2) and replace the broken code in step 11 with the good code from step 16.

Screenshot 1: broken code in step 11 
<img width="330" alt="Bildschirmfoto 2020-11-23 um 22 11 03" src="https://user-images.githubusercontent.com/64843796/100062769-70c1f780-2e30-11eb-96e5-52562ba0a14e.png">

Screenshot 2: good code in step 16
<img width="376" alt="Bildschirmfoto 2020-11-23 um 22 23 13" src="https://user-images.githubusercontent.com/64843796/100062797-7c152300-2e30-11eb-9ef9-d65b16738912.png">

**Comment by linker03** [comment]
I'll do it tomorrow.

**Comment by joe-the-ark** [comment]
Sure @linker03 – whenever suits you. Enjoy a great day!

**Comment by linker03** [comment]
@joe-the-ark Tell me, please how gradient should change depends on the score in the circle. How the circle should move horizontally depends on the score?

**Comment by joe-the-ark** [comment]
I think you can use the code from assessment.html and paste it to psychologischer - the screenshots are from the same game. In the assessment.html code all is good

**Comment by joe-the-ark** [comment]
@linker03 : the colouring is good. Gradients don't need to change. In assessment they are all good: green on left side (5 -> good values) and red on the right side (0 -> critical values)

The horizontal movement depends on the score, yes. If the score is 5 it should be on the left, if it is 2 1/2 in the middle ––– if you have difficulties implementing this, just skip the movement & but a bigger circle with a bigger number in the middle of the scale.

**Comment by joe-the-ark** [comment]
@linker03 
All good! Works!! Thank you so much!!! Kudos!!!!
